AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2

Style/CommentAnnotation:
  Enabled: false
