inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**'
    - 'bin/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Lint/MissingSuper:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2

Style/CommentAnnotation:
  Enabled: false
