AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2

Style/CommentAnnotation:
  Enabled: false
