version: '3'

volumes:
  postgres:

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
     - postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - .:/citizen-catalog
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts
    links:
      - db:postgres
    environment:
      DB_HOST: postgres
      PORT: 5000
    command: "/bin/sh -c 'while true; do sleep 60; done'"
