inherit_from: ../.rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
