# frozen_string_literal: true
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

CountryCode.create!(code: '+93', country_name: '+93 - Afeganistão')
CountryCode.create!(code: '+27', country_name: '+27 - África do Sul')
CountryCode.create!(code: '+355', country_name: '+355 - Albânia')
CountryCode.create!(code: '+49', country_name: '+49 - Alemanha')
CountryCode.create!(code: '+376', country_name: '+376 - Andorra')
CountryCode.create!(code: '+244', country_name: '+244 - Angola')
CountryCode.create!(code: '+1', country_name: '+1 - Anguilla')
CountryCode.create!(code: '+1', country_name: '+1 - Antígua e Barbuda')
CountryCode.create!(code: '+599', country_name: '+599 - Antilhas Holandesas')
CountryCode.create!(code: '+966', country_name: '+966 - Arábia Saudita')
CountryCode.create!(code: '+213', country_name: '+213 - Argélia')
CountryCode.create!(code: '+54', country_name: '+54 - Argentina')
CountryCode.create!(code: '+374', country_name: '+374 - Armênia')
CountryCode.create!(code: '+297', country_name: '+297 - Aruba')
CountryCode.create!(code: '+247', country_name: '+247 - Ascensão')
CountryCode.create!(code: '+61', country_name: '+61 - Austrália')
CountryCode.create!(code: '+43', country_name: '+43 - Áustria')
CountryCode.create!(code: '+994', country_name: '+994 - Azerbaijão')
CountryCode.create!(code: '+1', country_name: '+1 - Bahamas')
CountryCode.create!(code: '+880', country_name: '+880 - Bangladesh')
CountryCode.create!(code: '+1', country_name: '+1 - Barbados')
CountryCode.create!(code: '+973', country_name: '+973 - Bahrein')
CountryCode.create!(code: '+32', country_name: '+32 - Bélgica')
CountryCode.create!(code: '+501', country_name: '+501 - Belize')
CountryCode.create!(code: '+229', country_name: '+229 - Benim')
CountryCode.create!(code: '+1', country_name: '+1 - Bermudas')
CountryCode.create!(code: '+375', country_name: '+375 - Bielorrússia')
CountryCode.create!(code: '+591', country_name: '+591 - Bolívia')
CountryCode.create!(code: '+387', country_name: '+387 - Bósnia e Herzegovina')
CountryCode.create!(code: '+267', country_name: '+267 - Botswana')
CountryCode.create!(code: '+55', country_name: '+55 - Brasil')
CountryCode.create!(code: '+673', country_name: '+673 - Brunei')
CountryCode.create!(code: '+359', country_name: '+359 - Bulgária')
CountryCode.create!(code: '+226', country_name: '+226 - Burkina Faso')
CountryCode.create!(code: '+257', country_name: '+257 - Burundi')
CountryCode.create!(code: '+975', country_name: '+975 - Butão')
CountryCode.create!(code: '+238', country_name: '+238 - Cabo Verde')
CountryCode.create!(code: '+237', country_name: '+237 - Camarões')
CountryCode.create!(code: '+855', country_name: '+855 - Camboja')
CountryCode.create!(code: '+1', country_name: '+1 - Canadá')
CountryCode.create!(code: '+7', country_name: '+7 - Cazaquistão')
CountryCode.create!(code: '+237', country_name: '+237 - Chade')
CountryCode.create!(code: '+56', country_name: '+56 - Chile')
CountryCode.create!(code: '+86', country_name: '+86 - República Popular da China')
CountryCode.create!(code: '+357', country_name: '+357 - Chipre')
CountryCode.create!(code: '+57', country_name: '+57 - Colômbia')
CountryCode.create!(code: '+269', country_name: '+269 - Comores')
CountryCode.create!(code: '+242', country_name: '+242 - Congo-Brazzaville')
CountryCode.create!(code: '+243', country_name: '+243 - Congo-Kinshasa')
CountryCode.create!(code: '+850', country_name: '+850 - Coreia do Norte')
CountryCode.create!(code: '+82', country_name: '+82 - Coreia do Sul')
CountryCode.create!(code: '+225', country_name: '+225 - Costa do Marfim')
CountryCode.create!(code: '+506', country_name: '+506 - Costa Rica')
CountryCode.create!(code: '+385', country_name: '+385 - Croácia')
CountryCode.create!(code: '+53', country_name: '+53 - Cuba')
CountryCode.create!(code: '+45', country_name: '+45 - Dinamarca')
CountryCode.create!(code: '+253', country_name: '+253 - Djibuti')
CountryCode.create!(code: '+1', country_name: '+1 - Dominica')
CountryCode.create!(code: '+20', country_name: '+20 - Egipto')
CountryCode.create!(code: '+503', country_name: '+503 - El Salvador')
CountryCode.create!(code: '+971', country_name: '+971 - Emirados Árabes Unidos')
CountryCode.create!(code: '+593', country_name: '+593 - Equador')
CountryCode.create!(code: '+291', country_name: '+291 - Eritreia')
CountryCode.create!(code: '+421', country_name: '+421 - Eslováquia')
CountryCode.create!(code: '+386', country_name: '+386 - Eslovénia')
CountryCode.create!(code: '+34', country_name: '+34 - Espanha')
CountryCode.create!(code: '+1', country_name: '+1 - Estados Unidos')
CountryCode.create!(code: '+372', country_name: '+372 - Estónia')
CountryCode.create!(code: '+251', country_name: '+251 - Etiópia')
CountryCode.create!(code: '+679', country_name: '+679 - Fiji')
CountryCode.create!(code: '+63', country_name: '+63 - Filipinas')
CountryCode.create!(code: '+358', country_name: '+358 - Finlândia')
CountryCode.create!(code: '+33', country_name: '+33 - França')
CountryCode.create!(code: '+241', country_name: '+241 - Gabão')
CountryCode.create!(code: '+220', country_name: '+220 - Gâmbia')
CountryCode.create!(code: '+233', country_name: '+233 - Gana')
CountryCode.create!(code: '+995', country_name: '+995 - Geórgia')
CountryCode.create!(code: '+350', country_name: '+350 - Gibraltar')
CountryCode.create!(code: '+1', country_name: '+1 - Granada')
CountryCode.create!(code: '+30', country_name: '+30 - Grécia')
CountryCode.create!(code: '+299', country_name: '+299 - Groenlândia')
CountryCode.create!(code: '+590', country_name: '+590 - Guadalupe')
CountryCode.create!(code: '+671', country_name: '+671 - Guam')
CountryCode.create!(code: '+502', country_name: '+502 - Guatemala')
CountryCode.create!(code: '+592', country_name: '+592 - Guiana')
CountryCode.create!(code: '+594', country_name: '+594 - Guiana Francesa')
CountryCode.create!(code: '+224', country_name: '+224 - Guiné')
CountryCode.create!(code: '+245', country_name: '+245 - Guiné-Bissau')
CountryCode.create!(code: '+240', country_name: '+240 - Guiné Equatorial')
CountryCode.create!(code: '+509', country_name: '+509 - Haiti')
CountryCode.create!(code: '+504', country_name: '+504 - Honduras')
CountryCode.create!(code: '+852', country_name: '+852 - Hong Kong')
CountryCode.create!(code: '+36', country_name: '+36 - Hungria')
CountryCode.create!(code: '+967', country_name: '+967 - Iêmen')
CountryCode.create!(code: '+1', country_name: '+1 - Ilhas Cayman')
CountryCode.create!(code: '+672', country_name: '+672 - Ilha Christmas')
CountryCode.create!(code: '+672', country_name: '+672 - Ilhas Cocos')
CountryCode.create!(code: '+682', country_name: '+682 - Ilhas Cook')
CountryCode.create!(code: '+298', country_name: '+298 - Ilhas Féroe')
CountryCode.create!(code: '+672', country_name: '+672 - Ilha Heard e Ilhas McDonald')
CountryCode.create!(code: '+960', country_name: '+960 - Maldivas')
CountryCode.create!(code: '+500', country_name: '+500 - Ilhas Malvinas')
CountryCode.create!(code: '+1', country_name: '+1 - Ilhas Marianas do Norte')
CountryCode.create!(code: '+692', country_name: '+692 - Ilhas Marshall')
CountryCode.create!(code: '+672', country_name: '+672 - Ilha Norfolk')
CountryCode.create!(code: '+677', country_name: '+677 - Ilhas Salomão')
CountryCode.create!(code: '+1', country_name: '+1 - Ilhas Virgens Americanas')
CountryCode.create!(code: '+1', country_name: '+1 - Ilhas Virgens Britânicas')
CountryCode.create!(code: '+91', country_name: '+91 - Índia')
CountryCode.create!(code: '+62', country_name: '+62 - Indonésia')
CountryCode.create!(code: '+98', country_name: '+98 - Irã')
CountryCode.create!(code: '+964', country_name: '+964 - Iraque')
CountryCode.create!(code: '+353', country_name: '+353 - Irlanda')
CountryCode.create!(code: '+354', country_name: '+354 - Islândia')
CountryCode.create!(code: '+972', country_name: '<+972 - span class="flagicon">&nbsp;</span>Israel')
CountryCode.create!(code: '+39', country_name: '+39 - Itália')
CountryCode.create!(code: '+1', country_name: '+1 - Jamaica')
CountryCode.create!(code: '+81', country_name: '+81 - Japão')
CountryCode.create!(code: '+962', country_name: '+962 - Jordânia')
CountryCode.create!(code: '+686', country_name: '+686 - Kiribati')
CountryCode.create!(code: '+383', country_name: '+383 - Kosovo')
CountryCode.create!(code: '+965', country_name: '+965 - Kuwait')
CountryCode.create!(code: '+856', country_name: '+856 - Laos')
CountryCode.create!(code: '+266', country_name: '+266 - Lesoto')
CountryCode.create!(code: '+371', country_name: '+371 - Letônia')
CountryCode.create!(code: '+961', country_name: '+961 - Líbano')
CountryCode.create!(code: '+231', country_name: '+231 - Libéria')
CountryCode.create!(code: '+218', country_name: '+218 - Líbia')
CountryCode.create!(code: '+423', country_name: '+423 - Liechtenstein')
CountryCode.create!(code: '+370', country_name: '+370 - Lituânia')
CountryCode.create!(code: '+352', country_name: '+352 - Luxemburgo')
CountryCode.create!(code: '+853', country_name: '+853 - Macau')
CountryCode.create!(code: '+389', country_name: '+389 - República da Macedônia')
CountryCode.create!(code: '+261', country_name: '+261 - Madagascar')
CountryCode.create!(code: '+60', country_name: '+60 - Malásia')
CountryCode.create!(code: '+265', country_name: '+265 - Malawi')
CountryCode.create!(code: '+223', country_name: '+223 - Mali')
CountryCode.create!(code: '+356', country_name: '+356 - Malta')
CountryCode.create!(code: '+212', country_name: '+212 - Marrocos')
CountryCode.create!(code: '+596', country_name: '+596 - Martinica')
CountryCode.create!(code: '+230', country_name: '+230 - Maurícia')
CountryCode.create!(code: '+222', country_name: '+222 - Mauritânia')
CountryCode.create!(code: '+269', country_name: '+269 - Mayotte')
CountryCode.create!(code: '+52', country_name: '+52 - México')
CountryCode.create!(code: '+691', country_name: '+691 - Estados Federados da Micronésia')
CountryCode.create!(code: '+258', country_name: '+258 - Moçambique')
CountryCode.create!(code: '+373', country_name: '+373 - Moldávia')
CountryCode.create!(code: '+377', country_name: '+377 - Mônaco')
CountryCode.create!(code: '+976', country_name: '+976 - Mongólia')
CountryCode.create!(code: '+382', country_name: '+382 - Montenegro')
CountryCode.create!(code: '+1', country_name: '+1 - Montserrat')
CountryCode.create!(code: '+95', country_name: '+95 - Myanmar')
CountryCode.create!(code: '+264', country_name: '+264 - Namíbia')
CountryCode.create!(code: '+674', country_name: '+674 - Nauru')
CountryCode.create!(code: '+977', country_name: '+977 - Nepal')
CountryCode.create!(code: '+505', country_name: '+505 - Nicarágua')
CountryCode.create!(code: '+227', country_name: '+227 - Níger')
CountryCode.create!(code: '+234', country_name: '+234 - Nigéria')
CountryCode.create!(code: '+683', country_name: '+683 - Niue')
CountryCode.create!(code: '+47', country_name: '+47 - Noruega')
CountryCode.create!(code: '+687', country_name: '+687 - Nova Caledônia')
CountryCode.create!(code: '+64', country_name: '+64 - Nova Zelândia')
CountryCode.create!(code: '+968', country_name: '+968 - Omã')
CountryCode.create!(code: '+31', country_name: '+31 - Países Baixos')
CountryCode.create!(code: '+680', country_name: '+680 - Palau')
CountryCode.create!(code: '+970', country_name: '+970 - Palestina')
CountryCode.create!(code: '+507', country_name: '+507 - Panamá')
CountryCode.create!(code: '+675', country_name: '+675 - Papua-Nova Guiné')
CountryCode.create!(code: '+92', country_name: '+92 - Paquistão')
CountryCode.create!(code: '+595', country_name: '+595 - Paraguai')
CountryCode.create!(code: '+51', country_name: '+51 - Peru')
CountryCode.create!(code: '+689', country_name: '+689 - Polinésia Francesa')
CountryCode.create!(code: '+48', country_name: '+48 - Polônia')
CountryCode.create!(code: '+1', country_name: '+1 - Porto Rico')
CountryCode.create!(code: '+351', country_name: '+351 - Portugal')
CountryCode.create!(code: '+974', country_name: '+974 - Qatar')
CountryCode.create!(code: '+254', country_name: '+254 - Quênia')
CountryCode.create!(code: '+996', country_name: '+996 - Quirguistão')
CountryCode.create!(code: '+44', country_name: '+44 - Reino Unido')
CountryCode.create!(code: '+236', country_name: '+236 - República Centro-Africana')
CountryCode.create!(code: '+1', country_name: '+1 - República Dominicana')
CountryCode.create!(code: '+420', country_name: '+420 - República Tcheca')
CountryCode.create!(code: '+262', country_name: '+262 - Reunião')
CountryCode.create!(code: '+40', country_name: '+40 - Romênia')
CountryCode.create!(code: '+250', country_name: '+250 - Ruanda')
CountryCode.create!(code: '+7', country_name: '+7 - Rússia')
CountryCode.create!(code: '+212', country_name: '+212 - Saara Ocidental')
CountryCode.create!(code: '+685', country_name: '+685 - Samoa')
CountryCode.create!(code: '+1', country_name: '+1 - Samoa Americana')
CountryCode.create!(code: '+290', country_name: '+290 - Santa Helena (território)')
CountryCode.create!(code: '+1', country_name: '+1 - Santa Lúcia')
CountryCode.create!(code: '+1', country_name: '+1 - São Cristóvão e Nevis')
CountryCode.create!(code: '+378', country_name: '+378 - São Marinho')
CountryCode.create!(code: '+508', country_name: '+508 - Saint-Pierre e Miquelon')
CountryCode.create!(code: '+239', country_name: '+239 - São Tomé e Príncipe')
CountryCode.create!(code: '+1', country_name: '+1 - São Vicente e Granadinas')
CountryCode.create!(code: '+248', country_name: '+248 - Seicheles')
CountryCode.create!(code: '+221', country_name: '+221 - Senegal')
CountryCode.create!(code: '+232', country_name: '+232 - Serra Leoa')
CountryCode.create!(code: '+381', country_name: '+381 - Sérvia')
CountryCode.create!(code: '+65', country_name: '+65 - Singapura')
CountryCode.create!(code: '+963', country_name: '+963 - Síria')
CountryCode.create!(code: '+252', country_name: '+252 - Somália')
CountryCode.create!(code: '+94', country_name: '+94 - Sri Lanka')
CountryCode.create!(code: '+268', country_name: '+268 - Suazilândia')
CountryCode.create!(code: '+249', country_name: '+249 - Sudão')
CountryCode.create!(code: '+211', country_name: '+211 - Sudão do Sul')
CountryCode.create!(code: '+46', country_name: '+46 - Suécia')
CountryCode.create!(code: '+41', country_name: '+41 - Suíça')
CountryCode.create!(code: '+597', country_name: '+597 - Suriname')
CountryCode.create!(code: '+992', country_name: '+992 - Tadjiquistão')
CountryCode.create!(code: '+66', country_name: '+66 - Tailândia')
CountryCode.create!(code: '+886', country_name: '+886 - República da China')
CountryCode.create!(code: '+255', country_name: '+255 - Tanzânia')
CountryCode.create!(code: '+246', country_name: '+246 - Território Britânico do Oceano Índico')
CountryCode.create!(code: '+670', country_name: '+670 - Timor-Leste')
CountryCode.create!(code: '+228', country_name: '+228 - Togo')
CountryCode.create!(code: '+690', country_name: '+690 - Tokelau')
CountryCode.create!(code: '+676', country_name: '+676 - Tonga')
CountryCode.create!(code: '+1', country_name: '+1 - Trinidad e Tobago')
CountryCode.create!(code: '+216', country_name: '+216 - Tunísia')
CountryCode.create!(code: '+1', country_name: '+1 - Turcas e Caicos')
CountryCode.create!(code: '+993', country_name: '+993 - Turquemenistão')
CountryCode.create!(code: '+90', country_name: '+90 - Turquia')
CountryCode.create!(code: '+688', country_name: '+688 - Tuvalu')
CountryCode.create!(code: '+380', country_name: '+380 - Ucrânia')
CountryCode.create!(code: '+256', country_name: '+256 - Uganda')
CountryCode.create!(code: '+598', country_name: '+598 - Uruguai')
CountryCode.create!(code: '+998', country_name: '+998 - Uzbequistão')
CountryCode.create!(code: '+678', country_name: '+678 - Vanuatu')
CountryCode.create!(code: '+379', country_name: '+379 - Vaticano')
CountryCode.create!(code: '+58', country_name: '+58 - Venezuela')
CountryCode.create!(code: '+84', country_name: '+84 - Vietnã')
CountryCode.create!(code: '+681', country_name: '+681 - Wallis e Futuna')
CountryCode.create!(code: '+260', country_name: '+260 - Zâmbia')
CountryCode.create!(code: '+263', country_name: '+263 - Zimbábue')
